# Generated by Django 5.2 on 2025-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('tour_package_id', models.PositiveIntegerField()),
                ('tour_name', models.CharField(max_length=255)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
