# Generated by Django 5.2 on 2025-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_site', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('excerpt', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('MountainTrek', 'MountainTrek')], max_length=50)),
            ],
        ),
    ]
