# Generated by Django 5.2 on 2025-04-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_site', '0006_country_countrydescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='county_images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_info', to='Tour_site.country')),
            ],
        ),
    ]
